# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
group:
  synkron_led_blink:
    name: "Synkron Led blink"
    entities:
      - light.ju_udvendig_betjeningsskab_section_26

input_boolean: !include_dir_merge_named ./train/input_boolean

recorder:
  db_url: !secret maria_db

