# Individual input hub0
binary_sensor:
  - platform: gpio
    name: "_00"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_01"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 1
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_02"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 2
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_03"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 3
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_04"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_05"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_06"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 6
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_07"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 7
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_08"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 8
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_09"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_0A"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 10
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_0B"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 11
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_0C"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 12
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_0D"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 13
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_0E"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 14
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_0F"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 15
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
# Individual input hub1
#binary_sensor:
  - platform: gpio
    name: "_10"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_11"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 1
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_12"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 2
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_13"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 3
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_14"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_15"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_16"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 6
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_17"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 7
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_18"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 8
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_19"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_1A"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 10
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_1B"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 11
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_1C"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 12
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_1D"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 13
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_1E"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 14
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_1F"
    pin:
      mcp23xxx: ${id_mcp23017}1
      number: 15
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
# Individual input hub2
#binary_sensor:
  - platform: gpio
    name: "_20"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_21"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 1
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_22"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 2
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_23"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 3
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_24"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_25"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_26"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 6
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_27"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 7
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_28"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 8
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_29"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_2A"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 10
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_2B"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 11
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_2C"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 12
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_2D"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 13
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_2E"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 14
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_2F"
    pin:
      mcp23xxx: ${id_mcp23017}2
      number: 15
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
# Individual input hub3
#binary_sensor:
  - platform: gpio
    name: "_30"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_31"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 1
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_32"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 2
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_33"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 3
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_34"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_35"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_36"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 6
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_37"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 7
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_38"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 8
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_39"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_3A"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 10
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_3B"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 11
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_3C"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 12
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_3D"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 13
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_3E"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 14
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_3F"
    pin:
      mcp23xxx: ${id_mcp23017}3
      number: 15
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
