# Individual input hub0
binary_sensor:
  - platform: gpio
    name: "_00"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 0
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_01"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 1
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_02"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 2
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_03"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 3
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_04"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 4
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_05"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 5
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_06"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 6
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_07"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 7
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_08"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 8
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_09"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 9
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_10"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 10
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_11"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 11
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_12"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 12
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_13"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 13
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_14"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 14
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
  - platform: gpio
    name: "_15"
    pin:
      mcp23xxx: ${id_mcp23017}0
      number: 15
      mode:
        input: true
        pullup: true
      inverted: true
    filters:
      - delayed_off: ${track_delayed_off}
      - delayed_on: ${track_delayed_on}
