esphome:
  name: ${esphome_name}
  friendly_name: ${esphome_friendly_name}
  platform: ESP32
  board: esp32-poe-iso
  
ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO17_OUT
  phy_addr: 0
  power_pin: GPIO12

# Example configuration entry
logger:
#  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_omjk

# Example configuration entry
text_sensor:
  - platform: ethernet_info
    ip_address:
      name: "IP Address ${esphome_name}"
    dns_address:
      name: "DNS Address ${esphome_name}"
    mac_address:
      name: "MAC Address ${esphome_name}"

button:
  - platform: restart
    name: "Restart ${esphome_name}"

i2c:
  sda: 13
  scl: 16
  scan: True
  id: bus_a
  frequency: ${i2c_frequency}
