# https://community.home-assistant.io/t/wt32-eth01/540275
esphome:
  name: ${esphome_name}
  friendly_name: ${esphome_friendly_name}

esp32:
  board: wt32-eth01
  framework:
    type: arduino

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  #manual_ip:
  #  static_ip: 192.168.0.250
  #  gateway: 192.168.0.1
  #  subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_omjk

ota:
  password: !secret ota_pass_omjk
  #port: 3232

# ethernet_info
text_sensor:
  - platform: ethernet_info
    ip_address:
      name: ESP IP Address
    dns_address:
      name: ESP DNS Address

button:
  - platform: restart
    name: "Restart ${esphome_name}"

i2c:
  - id: ${i2c_id}
    sda: ${i2c_sda}
    scl: ${i2c_scl}
    scan: ${i2c_scan}  
    frequency: ${i2c_frequency}