esphome:
  name: ${esphome_name}
  friendly_name: ${esphome_friendly_name}

esp32:
  board: wt32-eth01 # https://docs.platformio.org/en/latest/boards/espressif32/wt32-eth01.html
  framework:
    type: arduino

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 0
  power_pin: GPIO16

# Enable logging
logger:

# Enable Home Assistant API
api:

button:
  - platform: restart
    name: "Restart ${esphome_name}"
