substitutions:
  esphome_name: "wt32-eth01-00"
  esphome_friendly_name: "WT32-eth01-00"

# I2C Port settings  
  i2c_sda: "33"  # WT32-ETH01 485_EN = Gpio 33 non standard i2c adress
  i2c_scl: "32"  # WT32-ETH01 CFG    = Gpio 32 non standard i2c adress 
  i2c_scan: "true"
  i2c_id: "bus_a"
  i2c_frequency: "10kHz"

# wt32-eth01 base config
<<: !include ./ESP32/.wt32-eth01base.yaml
