################################################################################
# Substitution Variables
################################################################################
substitutions:
  device_internal_name: esphome_study_wifi_static_ip
  device_friendly_name: ESPHome Study WiFi Static IP
  device_wifi_name: esphome-study-wifi-static-ip
  device_sampling_time: 30s
  device_static_ip: 192.168.0.227
  comment: "ESP32 WROOM 32D HW-394"

################################################################################
# Common Packages
################################################################################
packages:
  # Include ESPHome Board Configuration 
  # version: 2.0.9
  board: !include 
    file: boards/esp32/wroom_32d_hw_394.yaml
    vars:
      i2c_scan: true
      uart_baud_rate: 115200
      framework_version: recommended 

  # Include Common Core ESPHome definitions
  settings: !include 
    file: common/core/settings.yaml
    vars:
      time_region: Europe/Copenhagen

  # Include Common Network Definition
  wifi: !include common/network/wifi.yaml
  
  webserver: !include common/network/webserver.yaml

  ##############################################################################
  # Peripherals Package
  ##############################################################################


  ##############################################################################
  # Sensors Package
  ##############################################################################
  bh1750: !include 
    file: sensors/environment/bh1750.yaml
    vars:
      i2c_address: 0x23

################################################################################
# Parameter Change
################################################################################
i2c:
#  sda: GPIO14
#  scl: GPIO15
  scan: false

wifi:
  <<: !include common/network/static_ip.yaml
