################################################################################
# Secrets sample file
################################################################################
# API Encryption Key Generator: base64 string 
#     32Byte Base64 String https://generate.plus/en/base64
# Password Generator:
#     https://generate.plus/en/passwords
################################################################################
# Author: Svenn-Erik K. Thomsen
# Web: https://www.youtube.com/@sekt1953
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Use at your own risks!
################################################################################

# API
api_encryption_key: "api_encryption_key"

# OTA
ota_password: "ota_password"

# Your Wi-Fi SSID and password
wifi_ssid: "wifi_ssid"
wifi_password: "wifi_password"
ap_password: "ap_password"

# Network settings
gateway_address: 192.168.0.1
subnet_address: 255.255.255.0
dns_address: 1.1.1.1,8.8.8.8

# Webserver
web_server_user: "web_server_user"
web_server_password: "web_server_password"
