substitutions:
  esphome_name: "ju-pl-00"
  esphome_friendly_name: "Hjulby-Pult-Led-00"

# PCA9685 Kilde: https://esphome.io/components/output/pca9685
# id (Optional, ID): 
#   The id to use for this pca9685 component. 
#   Use this if you have multiple PCA9685s connected at the same time
  id_pca9685_0: "pca9685_hub0"
  id_pca9685_1: "pca9685_hub1"
  id_pca9685_2: "pca9685_hub2"
  id_pca9685_3: "pca9685_hub3"
  id_pca9685_4: "pca9685_hub4"
  id_pca9685_5: "pca9685_hub5"
  id_pca9685_6: "pca9685_hub6"
  id_pca9685_7: "pca9685_hub7"
  id_pca9685_8: "pca9685_hub8"
  id_pca9685_9: "pca9685_hub9"
  id_pca9685_A: "pca9685_hubA"
  id_pca9685_B: "pca9685_hubB"
  id_pca9685_C: "pca9685_hubC"
  id_pca9685_D: "pca9685_hubD"
  id_pca9685_E: "pca9685_hubE"
  id_pca9685_F: "pca9685_hubF"
  
# address (Optional, int): 
#   The I²C address of the driver. Defaults to 0x40.
  addr_pca9685_0: "0x40"
  addr_pca9685_1: "0x41"
  addr_pca9685_2: "0x42"

  addr_pca9685_3: "0x43"
  addr_pca9685_4: "0x44"
  addr_pca9685_5: "0x45"
  
  addr_pca9685_6: "0x46"
  addr_pca9685_7: "0x47"
  addr_pca9685_8: "0x48"
  
  addr_pca9685_9: "0x49"
  addr_pca9685_A: "0x4A"
  addr_pca9685_B: "0x4B"
  
  addr_pca9685_C: "0x4C"
  addr_pca9685_D: "0x4D"
  addr_pca9685_E: "0x4E"
  addr_pca9685_F: "0x4F"
  
# frequency (Optional, float): 
#   The frequency to let the component drive all PWM outputs at. 
#   Must be in range from 24Hz to 1525.88Hz. Default 1000Hz.  
  frequency_pca9685_0: 1000Hz
  frequency_pca9685_1: 1000Hz
  frequency_pca9685_2: 1000Hz
  frequency_pca9685_3: 1000Hz
  frequency_pca9685_4: 1000Hz
  frequency_pca9685_5: 1000Hz
  frequency_pca9685_6: 1000Hz
  frequency_pca9685_7: 1000Hz
  frequency_pca9685_8: 1000Hz
  frequency_pca9685_9: 1000Hz
  frequency_pca9685_A: 1000Hz
  frequency_pca9685_B: 1000Hz
  frequency_pca9685_C: 1000Hz
  frequency_pca9685_D: 1000Hz
  frequency_pca9685_E: 1000Hz
  frequency_pca9685_F: 1000Hz

# Light Transition length
  light_default_transition: "1s"
  light_flash_transition: "0s"

# I2C Port settings  
  i2c_sda: "21"
  i2c_scl: "22"
  i2c_scan: "true"
  i2c_id: "bus_a"
  i2c_frequency: "10kHz"
  
# ESP32 base config
<<: !include ./ESP32/.esp32base.yaml

# I2C_PWM_Output with PCA9685
<<: !include ./I2C_O_PCA9685/.pca9685_ids_ju-pl.yaml
<<: !include ./I2C_O_PCA9685/.pca9685_output_ju-pl.yaml
<<: !include ./I2C_O_PCA9685/.pca9685_light_ju-pl.yaml
