################################################################################
# ESP32-S3-ETH-Waveshare
################################################################################
# Source:
#   https://www.waveshare.com/esp32-s3-eth.htm?srsltid=AfmBOopikBak8QwEWdt9f0DMsj--HAiIWbsdRocID29ZegQRO9xj3I5B
#   https://www.waveshare.com/wiki/ESP32-S3-ETH#Schematic_Diagram
# 
# Key features include:
#   * Adopts ESP32-S3R8 high-performance chip with Xtensa 32-bit LX7 dual-core processor, capable of running at 240 MHz
#   * Integrated 512KB SRAM, 384KB ROM, 8MB PSRAM and 16MB Flash memory
#   * Integrated 2.4GHz Wi-Fi and Bluetooth 5 (LE) wireless communication, with an onboard antenna. Supports switching to use external antenna
#   * Onboard W5500 Ethernet chip for extending 10/100Mbps network port through SPI interface
#   * Optional for PoE module to realize Power over Ethernet function (IEEE 802.3af-compliant)
#   * Onboard camera interface, supports OV5640 and other mainstream cameras for image and video capture
#   * Onboard USB Type-C port for power supply, program downloading, and debugging, more convenient for development use
#   * Onboard TF card slot for external TF card storage of pictures or files
#   * Compatible with Pico header, onboard multiple peripheral interfaces, offering strong compatibility and expandability
# ------------------------------------------------------------------------------
# Usage:
#   Add the following code to package section in the device file
# ------------------------------------------------------------------------------
# packages:
#   board: !include 
#     file: boards/esp32/ESP32-S3-ETH-Waveshare.yaml
#     vars:
#       i2c_scan: true
#       uart_baud_rate: 115200
#       framework_version: recommended 
# ------------------------------------------------------------------------------
# Note about Framework: https://esphome.io/components/esp32/#framework   
# framework_version:
#  - dev         : Use the latest commit, note this may break at any time
#  - latest      : Use the latest release, even if it hasn’t been recommended yet.
#  - recommended : Use the recommended framework version.  
# ------------------------------------------------------------------------------
# Requirement: 
#   - Requires the following substitution in the device file:
#       - device_internal_name
#       - device_sampling_time
#
################################################################################
# PinOut; 
#   https://www.waveshare.com/img/devkit/ESP32-S3-ETH/ESP32-S3-ETH-details-15.jpg
#
# Safe Pins to Use:             SD Card:
#   Pin4  - GPIO48              SD_MOSI - GPIO6
#   Pin5  - GPIO47              SD_MISO - GPIO5
#   Pin6  - GPIO46              SD_CLK  - GPIO7
#   Pin7  - GPIO45              SD_CS   - GPIO4
#   Pin9  - GPIO42
#   Pin10 - GPIO41              W5500 Ethernet:
#   Pin11 - GPIO40              ETH_MOSI - GPIO11
#   Pin12 - GPIO39              ETH_MISO - GPIO12
#   Pin14 - GPIO38              ETH_CLK  - GPIO13
#   Pin15 - GPIO37              ETH_CS   - GPIO14
#   Pin16 - GPIO36              ETH_INT  - GPIO10
#   Pin17 - GPIO35              ETH_RST  - GPIO9
#   Pin19 - GPIO34
#   Pin20 - GPIO33              RGB DataIn:
#   Pin25 - GPIO1               Pin35    - GPIO21 
#   Pin26 - GPIO2 
#   Pin27 - GPIO3               BOOT:
#   Pin29 - GPIO15              Pin24    - GPIO0
#   Pin31 - GPIO18
#   Pin32 - GPIO16              RESET:
#   Pin34 - GPIO17              Pin30    - CHIP_UP
#
################################################################################
# Author: Svenn-Erik K. Thomsen
# Web: https://www.youtube.com/@sekt1953
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
# ------------------------------------------------------------------------------
# Notes:
#     - ikke Tested OK
################################################################################
# Board Specific Configurations
# ------------------------------------------------------------------------------
# This specification file is specific to the ESP32 S3 N16R8 development board!
# Do not try to use another!
# ------------------------------------------------------------------------------
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 16MB
  framework:
    type: esp-idf
    platform_version: 6.9.0
    advanced:
      ignore_efuse_mac_crc_check: false

# Status led
status_led:
  id: ${device_internal_name}_status_led
  pin:
    number: GPIO21
    inverted: false
