################################################################################
# Common Network - Ethernet LAN8720
################################################################################
# Source: 
#   - https://esphome.io/components/ethernet/
#   - https://esphome.io/components/ethernet/#rmii-configuration-variables
# Usage:
#   Add the following code to package section in the device file
# ------------------------------------------------------------------------------
# packages:
#   board: !include 
#     file: common/network/ethernet_lan8720.yaml
#     vars:
#       ethernet_lan8720_mdc_pin: GPIO23
#       ethernet_lan8720_mdio_pin: GPIO18
#       ethernet_lan8720_clk_pin: GPIO17
#       ethernet_lan8720_power_pin: GPIO12
#
################################################################################
# Author: Svenn-Erik K. Thomsen
# YouTube: https://www.youtube.com/@sekt1953
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
################################################################################
# Notes:
#     - ikke Tested OK
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Meaning that it works on my setup but it may not work on yours.
################################################################################
ethernet:
  type: LAN8720
  mdc_pin: GPIOXX     ${ethernet_lan8720_mdc_pin}
  mdio_pin: GPIOXX    ${ethernet_lan8720_mdio_pin}
  clk:
    pin: GPIO17       ${ethernet_lan8720_clk_pin}
    mode: CLK_OUT
  phy_addr: 0
  power_pin: GPIO12   ${ethernet_lan8720_power_pin}
