################################################################################
# WiFi Dynamic IP Component for ESP32
################################################################################
# Usage:
#   Add the following code to package section in the device file
# ------------------------------------------------------------------------------
# packages:
#   wifi: !include common/network/wifi_dynamicip.yaml
# ------------------------------------------------------------------------------
# Requirement: 
#   - Requires the following substitution in the device file:
#       - device_wifi_name:
#
#   - Requires the following from the secrets file:
#       - wifi_ssid:
#       - wifi_password;
#       - ap_password:
#
################################################################################
# Author: Svenn-Erik K. Thomsen
# YouTube: https://www.youtube.com/@sekt1953
# Version: 1.0.0
# Licence: CCO 1.0 https://creativecommons.org/publicdomain/zero/1.0/
################################################################################
# Notes:
#     - ikke Tested OK
# ------------------------------------------------------------------------------
# WARNING:
# This code carries a "It works on my setup" disclaimer!
# Meaning that it works on my setup but it may not work on yours.
################################################################################
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  fast_connect: true
  domain: .local
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_wifi_name}
    password: !secret ap_password

captive_portal:
