substitutions:
  esphome_name: "ju-pl-01"
  esphome_friendly_name: "Hjulby-Pult-Led-01"

# PCA9685 Kilde: https://esphome.io/components/output/pca9685
# id (Optional, ID): 
#   The id to use for this pca9685 component. 
#   Use this if you have multiple PCA9685s connected at the same time
  id_pca9685: "pca9685_hub"
  
# frequency (Optional, float): 
#   The frequency to let the component drive all PWM outputs at. 
#   Must be in range from 24Hz to 1525.88Hz. Default 1000Hz.  
  frequency_pca9685: 1000Hz

# Light Transition length
  light_default_transition: "0s"
  light_flash_transition: "0s"

# PCF8574N & PCF8575
# 8bit portudvidelse I2C (2 wire) interface DIL16 Adresserbar til 
  id_pcf8574: "pcf8574_hub"
  id_pcf8574_0: "pcf8574_hub0"
  id_pcf8574_1: "pcf8574_hub1"
  id_pcf8574_2: "pcf8574_hub2"
  id_pcf8574_3: "pcf8574_hub3"
  id_pcf8574_4: "pcf8574_hub4"
  id_pcf8574_5: "pcf8574_hub5"
  id_pcf8574_6: "pcf8574_hub6"
  id_pcf8574_7: "pcf8574_hub7"
  
# hex:  0x20 0x21 0x22 0x23 0x24 0x25 0x26 0x27
  addr_pcf8574_0: "0x20"
  addr_pcf8574_1: "0x21"
  addr_pcf8574_2: "0x22"
  addr_pcf8574_3: "0x23"
  addr_pcf8574_4: "0x24"
  addr_pcf8574_5: "0x25"
  addr_pcf8574_6: "0x26"
  addr_pcf8574_7: "0x27"

# Delay before track occupied on/off
  track_delayed_on: 12ms
  track_delayed_off: 1000ms

# I2C Port settings  
  i2c_sda: "21"
  i2c_scl: "22"
  i2c_scan: "true"
  i2c_id: "bus_a"
  i2c_frequency: "10kHz"


