# I2C_IO_PCF8574
pcf8574:
  - id: ${id_pcf8574}0
    address: "0x20"
    pcf8575: false
  - id: ${id_pcf8574}1
    address: "0x21"
    pcf8575: false
  - id: ${id_pcf8574}2
    address: "0x22"
    pcf8575: false
  - id: ${id_pcf8574}3
    address: "0x23"
    pcf8575: false
