substitutions:
  esphome_name: "ju-bd-00"
  esphome_friendly_name: "Hjulby-Block-Detection-00"

# PCA9685 Kilde: https://esphome.io/components/output/pca9685
# id (Optional, ID): 
#   The id to use for this pca9685 component. 
#   Use this if you have multiple PCA9685s connected at the same time
  id_pca9685: "pca9685_hub"
  
# frequency (Optional, float): 
#   The frequency to let the component drive all PWM outputs at. 
#   Must be in range from 24Hz to 1525.88Hz. Default 1000Hz.  
  frequency_pca9685: 1000Hz

# Light Transition length
  light_default_transition: "0s"
  light_flash_transition: "0s"

# PCF8574N & PCF8575
# 8bit portudvidelse I2C (2 wire) interface DIL16 Adresserbar til 
  id_pcf8574: "pcf8574_hub"

# Delay before track occupied on/off
  track_delayed_on: 12ms
  track_delayed_off: 1000ms

# I2C Port settings  
  i2c_sda: "21"
  i2c_scl: "22"
  i2c_scan: "true"
  i2c_id: "bus_a"
  i2c_frequency: "10kHz"

# ESP32 base config
<<: !include ./ESP32/.esp32dev.yaml    

# I2C_IO_Interface with PCF8574
<<: !include ./I2C_IO_PCF8574/ju/ju/.pcf8574_ids_ju.yaml
<<: !include ./I2C_IO_PCF8574/ju/ju/.pcf8574_input_ju.yaml
