- trigger:
    # 101+ ju_udvendig_betjeningsskab_00
    - trigger: state
      entity_id:
        - binary_sensor.ju_udvendig_betjeningsskab_00
      to: off
      id: Ju_101+
      variables:
        Ju-TiS_101:
        Ju-Led_101a:
        Ju-Led_101b:
        Ju-Led_101-:
        Ju_Mo+_101a:
        Ju_Mo-_101a:
        Ju_Mo+_101b:
        Ju_Mo-_101b:
        Ju_Tb+_101a:
        Ju_Tb-_101a:
        Ju_Tb+_101b:
        ju_Tb-_101b:
  sensor:
    - name: ju-isolation
      state: "{{ trigger.id }}, to: {{ trigger.to_state.state }}, from: {{ trigger.from_state.state }}"
      attributes:
        trigger-id: "{{ trigger.id }}"
        Ju-Ub-Tis:
        Ju-ub-Led_a:
        Ju-Ub-Led_b:
        Ju-ub-Led_-:

