substitutions:
  esphome_name: "xx-l-00"
  esphome_friendly_name: "XX-Led-00"

# LED PCA9685

# PCA9685 Kilde: https://esphome.io/components/output/pca9685
# id (Optional, ID): 
#   The id to use for this pca9685 component. 
#   Use this if you have multiple PCA9685s connected at the same time
  id_pca9685_0: "pca9685_hub0"
  id_pca9685_1: "pca9685_hub1"
  id_pca9685_2: "pca9685_hub2"
  id_pca9685_3: "pca9685_hub3"
  id_pca9685_4: "pca9685_hub4"
  id_pca9685_5: "pca9685_hub5"
  id_pca9685_6: "pca9685_hub6"
  id_pca9685_7: "pca9685_hub7"
  id_pca9685_8: "pca9685_hub8"
  id_pca9685_9: "pca9685_hub9"
  id_pca9685_A: "pca9685_hubA"
  id_pca9685_B: "pca9685_hubB"
  id_pca9685_C: "pca9685_hubC"
  id_pca9685_D: "pca9685_hubD"
  id_pca9685_E: "pca9685_hubE"
  id_pca9685_F: "pca9685_hubF"
  
# address (Optional, int): 
#   The I²C address of the driver. Defaults to 0x40.
  addr_pca9685_0: "0x40"
  addr_pca9685_1: "0x41"
  addr_pca9685_2: "0x42"

  addr_pca9685_3: "0x43"
  addr_pca9685_4: "0x44"
  addr_pca9685_5: "0x45"
  
  addr_pca9685_6: "0x46"
  addr_pca9685_7: "0x47"
  addr_pca9685_8: "0x48"
  
  addr_pca9685_9: "0x49"
  addr_pca9685_A: "0x4A"
  addr_pca9685_B: "0x4B"
  
  addr_pca9685_C: "0x4C"
  addr_pca9685_D: "0x4D"
  addr_pca9685_E: "0x4E"
  addr_pca9685_F: "0x4F"
  
# frequency (Optional, float): 
#   The frequency to let the component drive all PWM outputs at. 
#   Must be in range from 24Hz to 1525.88Hz. Default 1000Hz.  
  pwm_frequency: 1000Hz

# Light Transition length
  light_default_transition: "1s"
  light_flash_transition: "0s"

# IO PCF8574

# PCF8574N & PCF8575
# 8bit portudvidelse I2C (2 wire) interface DIL16 Adresserbar til 
  id_pcf8574_0: "pcf8574_hub0"
  id_pcf8574_1: "pcf8574_hub1"
  id_pcf8574_2: "pcf8574_hub2"
  id_pcf8574_3: "pcf8574_hub3"
  id_pcf8574_4: "pcf8574_hub4"
  id_pcf8574_5: "pcf8574_hub5"
  id_pcf8574_6: "pcf8574_hub6"
  id_pcf8574_7: "pcf8574_hub7"
  
# hex:  0x20 0x21 0x22 0x23 0x24 0x25 0x26 0x27
  addr_pcf8574_0: "0x20"
  addr_pcf8574_1: "0x21"
  addr_pcf8574_2: "0x22"
  addr_pcf8574_3: "0x23"
  addr_pcf8574_4: "0x24"
  addr_pcf8574_5: "0x25"
  addr_pcf8574_6: "0x26"
  addr_pcf8574_7: "0x27"

# Debouncing Values 
# Some binary sensors are a bit unstable and quickly transition 
# between the ON and OFF state while they’re pressed. To fix this 
# and debounce the signal, use the binary sensor filters:
# https://esphome.io/components/binary_sensor/gpio#debouncing-values
  track_delayed_off: 1000ms
  track_delayed_on: 12ms

# I2C Port settings  
# https://esphome.io/components/i2c#i2c-bus

# I2C Port settings  
  i2c_sda: "21"
  i2c_scl: "22"
  i2c_scan: "true"
  i2c_id: "bus_a"
  i2c_frequency: "10kHz"

