# Light Component kilde: https://esphome.io/components/light/
# Monochromatic Light Kilde: https://esphome.io/components/light/monochromatic#monochromatic-light
#   Configuration variables:
#     name (Required, string): The name of the light.
#     output (Required, ID): The id of the float Output Component to use for this light.
#     effects (Optional, list): A list of light effects to use for this light.
#     id (Optional, ID): Manually specify the ID used for code generation.
light:
# Hub0
  - platform: monochromatic
    name: '_00'
    default_transition_length: 0s
    output: pwm00
  - platform: monochromatic
    name: '_01'
    default_transition_length: 0s
    output: pwm01
  - platform: monochromatic
    name: '_02'
    default_transition_length: 0s
    output: pwm02
  - platform: monochromatic
    name: '_03'
    default_transition_length: 0s
    output: pwm03
  - platform: monochromatic
    name: '_04'
    default_transition_length: 0s
    output: pwm04
  - platform: monochromatic
    name: '_05'
    default_transition_length: 0s
    output: pwm05
  - platform: monochromatic
    name: '_06'
    default_transition_length: 0s
    output: pwm06
  - platform: monochromatic
    name: '_07'
    default_transition_length: 0s
    output: pwm07
  - platform: monochromatic
    name: '_08'
    default_transition_length: 0s
    output: pwm08
  - platform: monochromatic
    name: '_09'
    default_transition_length: 0s
    output: pwm09
  - platform: monochromatic
    name: '_0A'
    default_transition_length: 0s
    output: pwm0a
  - platform: monochromatic
    name: '_0B'
    default_transition_length: 0s
    output: pwm0b
  - platform: monochromatic
    name: '_0C'
    default_transition_length: 0s
    output: pwm0c
  - platform: monochromatic
    name: '_0D'
    default_transition_length: 0s
    output: pwm0d
  - platform: monochromatic
    name: '_0E'
    default_transition_length: 0s
    output: pwm0e
  - platform: monochromatic
    name: '_0F'
    default_transition_length: 0s
    output: pwm0f
# Hub1
  - platform: monochromatic
    name: '_10'
    default_transition_length: 0s
    output: pwm10
  - platform: monochromatic
    name: '_11'
    default_transition_length: 0s
    output: pwm11
  - platform: monochromatic
    name: '_12'
    default_transition_length: 0s
    output: pwm12
  - platform: monochromatic
    name: '_13'
    default_transition_length: 0s
    output: pwm13
  - platform: monochromatic
    name: '_14'
    default_transition_length: 0s
    output: pwm14
  - platform: monochromatic
    name: '_15'
    default_transition_length: 0s
    output: pwm15
  - platform: monochromatic
    name: '_16'
    default_transition_length: 0s
    output: pwm16
  - platform: monochromatic
    name: '_17'
    default_transition_length: 0s
    output: pwm17
  - platform: monochromatic
    name: '_18'
    default_transition_length: 0s
    output: pwm18
  - platform: monochromatic
    name: '_19'
    default_transition_length: 0s
    output: pwm19
  - platform: monochromatic
    name: '_1A'
    default_transition_length: 0s
    output: pwm1a
  - platform: monochromatic
    name: '_1B'
    default_transition_length: 0s
    output: pwm1b
  - platform: monochromatic
    name: '_1C'
    default_transition_length: 0s
    output: pwm1c
  - platform: monochromatic
    name: '_1D'
    default_transition_length: 0s
    output: pwm1d
  - platform: monochromatic
    name: '_1E'
    default_transition_length: 0s
    output: pwm1e
  - platform: monochromatic
    name: '_1F'
    default_transition_length: 0s
    output: pwm1f
# Hub2
  - platform: monochromatic
    name: '_20'
    default_transition_length: 0s
    output: pwm20
  - platform: monochromatic
    name: '_21'
    default_transition_length: 0s
    output: pwm21
  - platform: monochromatic
    name: '_22'
    default_transition_length: 0s
    output: pwm22
  - platform: monochromatic
    name: '_23'
    default_transition_length: 0s
    output: pwm23
  - platform: monochromatic
    name: '_24'
    default_transition_length: 0s
    output: pwm24
  - platform: monochromatic
    name: '_25'
    default_transition_length: 0s
    output: pwm25
  - platform: monochromatic
    name: '_26'
    default_transition_length: 0s
    output: pwm26
  - platform: monochromatic
    name: '_27'
    default_transition_length: 0s
    output: pwm27
  - platform: monochromatic
    name: '_28'
    default_transition_length: 0s
    output: pwm28
  - platform: monochromatic
    name: '_29'
    default_transition_length: 0s
    output: pwm29
  - platform: monochromatic
    name: '_2A'
    default_transition_length: 0s
    output: pwm2a
  - platform: monochromatic
    name: '_2B'
    default_transition_length: 0s
    output: pwm2b
  - platform: monochromatic
    name: '_2C'
    default_transition_length: 0s
    output: pwm2c
  - platform: monochromatic
    name: '_2D'
    default_transition_length: 0s
    output: pwm2d
  - platform: monochromatic
    name: '_2E'
    default_transition_length: 0s
    output: pwm2e
  - platform: monochromatic
    name: '_2F'
    default_transition_length: 0s
    output: pwm2f
# Hub3
  - platform: monochromatic
    name: '_30'
    default_transition_length: 0s
    output: pwm30
  - platform: monochromatic
    name: '_31'
    default_transition_length: 0s
    output: pwm31
  - platform: monochromatic
    name: '_32'
    default_transition_length: 0s
    output: pwm32
  - platform: monochromatic
    name: '_33'
    default_transition_length: 0s
    output: pwm33
  - platform: monochromatic
    name: '_34'
    default_transition_length: 0s
    output: pwm34
  - platform: monochromatic
    name: '_35'
    default_transition_length: 0s
    output: pwm35
  - platform: monochromatic
    name: '_36'
    default_transition_length: 0s
    output: pwm36
  - platform: monochromatic
    name: '_37'
    default_transition_length: 0s
    output: pwm37
  - platform: monochromatic
    name: '_38'
    default_transition_length: 0s
    output: pwm38
  - platform: monochromatic
    name: '_39'
    default_transition_length: 0s
    output: pwm39
  - platform: monochromatic
    name: '_3A'
    default_transition_length: 0s
    output: pwm3a
  - platform: monochromatic
    name: '_3B'
    default_transition_length: 0s
    output: pwm3b
  - platform: monochromatic
    name: '_3C'
    default_transition_length: 0s
    output: pwm3c
  - platform: monochromatic
    name: '_3D'
    default_transition_length: 0s
    output: pwm3d
  - platform: monochromatic
    name: '_3E'
    default_transition_length: 0s
    output: pwm3e
  - platform: monochromatic
    name: '_3F'
    default_transition_length: 0s
    output: pwm3f
# Hub4
  - platform: monochromatic
    name: '_40'
    default_transition_length: 0s
    output: pwm40
  - platform: monochromatic
    name: '_41'
    default_transition_length: 0s
    output: pwm41
  - platform: monochromatic
    name: '_42'
    default_transition_length: 0s
    output: pwm42
  - platform: monochromatic
    name: '_43'
    default_transition_length: 0s
    output: pwm43
  - platform: monochromatic
    name: '_44'
    default_transition_length: 0s
    output: pwm44
  - platform: monochromatic
    name: '_45'
    default_transition_length: 0s
    output: pwm45
  - platform: monochromatic
    name: '_46'
    default_transition_length: 0s
    output: pwm46
  - platform: monochromatic
    name: '_47'
    default_transition_length: 0s
    output: pwm47
  - platform: monochromatic
    name: '_48'
    default_transition_length: 0s
    output: pwm48
  - platform: monochromatic
    name: '_49'
    default_transition_length: 0s
    output: pwm49
  - platform: monochromatic
    name: '_4A'
    default_transition_length: 0s
    output: pwm4a
  - platform: monochromatic
    name: '_4B'
    default_transition_length: 0s
    output: pwm4b
  - platform: monochromatic
    name: '_4C'
    default_transition_length: 0s
    output: pwm4c
  - platform: monochromatic
    name: '_4D'
    default_transition_length: 0s
    output: pwm4d
  - platform: monochromatic
    name: '_4E'
    default_transition_length: 0s
    output: pwm4e
  - platform: monochromatic
    name: '_4F'
    default_transition_length: 0s
    output: pwm4f
# Hub5
  - platform: monochromatic
    name: '_50'
    default_transition_length: 0s
    output: pwm50
  - platform: monochromatic
    name: '_51'
    default_transition_length: 0s
    output: pwm51
  - platform: monochromatic
    name: '_52'
    default_transition_length: 0s
    output: pwm52
  - platform: monochromatic
    name: '_53'
    default_transition_length: 0s
    output: pwm53
  - platform: monochromatic
    name: '_54'
    default_transition_length: 0s
    output: pwm54
  - platform: monochromatic
    name: '_55'
    default_transition_length: 0s
    output: pwm55
  - platform: monochromatic
    name: '_56'
    default_transition_length: 0s
    output: pwm56
  - platform: monochromatic
    name: '_57'
    default_transition_length: 0s
    output: pwm57
  - platform: monochromatic
    name: '_58'
    default_transition_length: 0s
    output: pwm58
  - platform: monochromatic
    name: '_59'
    default_transition_length: 0s
    output: pwm59
  - platform: monochromatic
    name: '_5A'
    default_transition_length: 0s
    output: pwm5a
  - platform: monochromatic
    name: '_5B'
    default_transition_length: 0s
    output: pwm5b
  - platform: monochromatic
    name: '_5C'
    default_transition_length: 0s
    output: pwm5c
  - platform: monochromatic
    name: '_5D'
    default_transition_length: 0s
    output: pwm5d
  - platform: monochromatic
    name: '_5E'
    default_transition_length: 0s
    output: pwm5e
  - platform: monochromatic
    name: '_5F'
    default_transition_length: 0s
    output: pwm5f
# Hub6
  - platform: monochromatic
    name: '_60'
    default_transition_length: 0s
    output: pwm60
  - platform: monochromatic
    name: '_61'
    default_transition_length: 0s
    output: pwm61
  - platform: monochromatic
    name: '_62'
    default_transition_length: 0s
    output: pwm62
  - platform: monochromatic
    name: '_63'
    default_transition_length: 0s
    output: pwm63
  - platform: monochromatic
    name: '_64'
    default_transition_length: 0s
    output: pwm64
  - platform: monochromatic
    name: '_65'
    default_transition_length: 0s
    output: pwm65
  - platform: monochromatic
    name: '_66'
    default_transition_length: 0s
    output: pwm66
  - platform: monochromatic
    name: '_67'
    default_transition_length: 0s
    output: pwm67
  - platform: monochromatic
    name: '_68'
    default_transition_length: 0s
    output: pwm68
  - platform: monochromatic
    name: '_69'
    default_transition_length: 0s
    output: pwm69
  - platform: monochromatic
    name: '_6A'
    default_transition_length: 0s
    output: pwm6a
  - platform: monochromatic
    name: '_6B'
    default_transition_length: 0s
    output: pwm6b
  - platform: monochromatic
    name: '_6C'
    default_transition_length: 0s
    output: pwm6c
  - platform: monochromatic
    name: '_6D'
    default_transition_length: 0s
    output: pwm6d
  - platform: monochromatic
    name: '_6E'
    default_transition_length: 0s
    output: pwm6e
  - platform: monochromatic
    name: '_6F'
    default_transition_length: 0s
    output: pwm6f
# Hub7
  - platform: monochromatic
    name: '_70'
    default_transition_length: 0s
    output: pwm70
  - platform: monochromatic
    name: '_71'
    default_transition_length: 0s
    output: pwm71
  - platform: monochromatic
    name: '_72'
    default_transition_length: 0s
    output: pwm72
  - platform: monochromatic
    name: '_73'
    default_transition_length: 0s
    output: pwm73
  - platform: monochromatic
    name: '_74'
    default_transition_length: 0s
    output: pwm74
  - platform: monochromatic
    name: '_75'
    default_transition_length: 0s
    output: pwm75
  - platform: monochromatic
    name: '_76'
    default_transition_length: 0s
    output: pwm76
  - platform: monochromatic
    name: '_77'
    default_transition_length: 0s
    output: pwm77
  - platform: monochromatic
    name: '_78'
    default_transition_length: 0s
    output: pwm78
  - platform: monochromatic
    name: '_79'
    default_transition_length: 0s
    output: pwm79
  - platform: monochromatic
    name: '_7A'
    default_transition_length: 0s
    output: pwm7a
  - platform: monochromatic
    name: '_7B'
    default_transition_length: 0s
    output: pwm7b
  - platform: monochromatic
    name: '_7C'
    default_transition_length: 0s
    output: pwm7c
  - platform: monochromatic
    name: '_7D'
    default_transition_length: 0s
    output: pwm7d
  - platform: monochromatic
    name: '_7E'
    default_transition_length: 0s
    output: pwm7e
  - platform: monochromatic
    name: '_7F'
    default_transition_length: 0s
    output: pwm7f
# Hub8
  - platform: monochromatic
    name: '_80'
    default_transition_length: 0s
    output: pwm80
  - platform: monochromatic
    name: '_81'
    default_transition_length: 0s
    output: pwm81
  - platform: monochromatic
    name: '_82'
    default_transition_length: 0s
    output: pwm82
  - platform: monochromatic
    name: '_83'
    default_transition_length: 0s
    output: pwm83
  - platform: monochromatic
    name: '_84'
    default_transition_length: 0s
    output: pwm84
  - platform: monochromatic
    name: '_85'
    default_transition_length: 0s
    output: pwm85
  - platform: monochromatic
    name: '_86'
    default_transition_length: 0s
    output: pwm86
  - platform: monochromatic
    name: '_87'
    default_transition_length: 0s
    output: pwm87
  - platform: monochromatic
    name: '_88'
    default_transition_length: 0s
    output: pwm88
  - platform: monochromatic
    name: '_89'
    default_transition_length: 0s
    output: pwm89
  - platform: monochromatic
    name: '_8A'
    default_transition_length: 0s
    output: pwm8a
  - platform: monochromatic
    name: '_8B'
    default_transition_length: 0s
    output: pwm8b
  - platform: monochromatic
    name: '_8C'
    default_transition_length: 0s
    output: pwm8c
  - platform: monochromatic
    name: '_8D'
    default_transition_length: 0s
    output: pwm8d
  - platform: monochromatic
    name: '_8E'
    default_transition_length: 0s
    output: pwm8e
  - platform: monochromatic
    name: '_8F'
    default_transition_length: 0s
    output: pwm8f
# Hub9
  - platform: monochromatic
    name: '_90'
    default_transition_length: 0s
    output: pwm90
  - platform: monochromatic
    name: '_91'
    default_transition_length: 0s
    output: pwm91
  - platform: monochromatic
    name: '_92'
    default_transition_length: 0s
    output: pwm92
  - platform: monochromatic
    name: '_93'
    default_transition_length: 0s
    output: pwm93
  - platform: monochromatic
    name: '_94'
    default_transition_length: 0s
    output: pwm94
  - platform: monochromatic
    name: '_95'
    default_transition_length: 0s
    output: pwm95
  - platform: monochromatic
    name: '_96'
    default_transition_length: 0s
    output: pwm96
  - platform: monochromatic
    name: '_97'
    default_transition_length: 0s
    output: pwm97
  - platform: monochromatic
    name: '_98'
    default_transition_length: 0s
    output: pwm98
  - platform: monochromatic
    name: '_99'
    default_transition_length: 0s
    output: pwm99
  - platform: monochromatic
    name: '_9A'
    default_transition_length: 0s
    output: pwm9a
  - platform: monochromatic
    name: '_9B'
    default_transition_length: 0s
    output: pwm9b
  - platform: monochromatic
    name: '_9C'
    default_transition_length: 0s
    output: pwm9c
  - platform: monochromatic
    name: '_9D'
    default_transition_length: 0s
    output: pwm9d
  - platform: monochromatic
    name: '_9E'
    default_transition_length: 0s
    output: pwm9e
  - platform: monochromatic
    name: '_9F'
    default_transition_length: 0s
    output: pwm9f
# HubA
  - platform: monochromatic
    name: '_A0'
    default_transition_length: 0s
    output: pwmA0
  - platform: monochromatic
    name: '_A1'
    default_transition_length: 0s
    output: pwmA1
  - platform: monochromatic
    name: '_A2'
    default_transition_length: 0s
    output: pwmA2
  - platform: monochromatic
    name: '_A3'
    default_transition_length: 0s
    output: pwmA3
  - platform: monochromatic
    name: '_A4'
    default_transition_length: 0s
    output: pwmA4
  - platform: monochromatic
    name: '_A5'
    default_transition_length: 0s
    output: pwmA5
  - platform: monochromatic
    name: '_A6'
    default_transition_length: 0s
    output: pwmA6
  - platform: monochromatic
    name: '_A7'
    default_transition_length: 0s
    output: pwmA7
  - platform: monochromatic
    name: '_A8'
    default_transition_length: 0s
    output: pwmA8
  - platform: monochromatic
    name: '_A9'
    default_transition_length: 0s
    output: pwmA9
  - platform: monochromatic
    name: '_AA'
    default_transition_length: 0s
    output: pwmAa
  - platform: monochromatic
    name: '_AB'
    default_transition_length: 0s
    output: pwmAb
  - platform: monochromatic
    name: '_AC'
    default_transition_length: 0s
    output: pwmAc
  - platform: monochromatic
    name: '_AD'
    default_transition_length: 0s
    output: pwmAd
  - platform: monochromatic
    name: '_AE'
    default_transition_length: 0s
    output: pwmAe
  - platform: monochromatic
    name: '_AF'
    default_transition_length: 0s
    output: pwmAf
# HubB
  - platform: monochromatic
    name: '_B0'
    default_transition_length: 0s
    output: pwmB0
  - platform: monochromatic
    name: '_B1'
    default_transition_length: 0s
    output: pwmB1
  - platform: monochromatic
    name: '_B2'
    default_transition_length: 0s
    output: pwmB2
  - platform: monochromatic
    name: '_B3'
    default_transition_length: 0s
    output: pwmB3
  - platform: monochromatic
    name: '_B4'
    default_transition_length: 0s
    output: pwmB4
  - platform: monochromatic
    name: '_B5'
    default_transition_length: 0s
    output: pwmB5
  - platform: monochromatic
    name: '_B6'
    default_transition_length: 0s
    output: pwmB6
  - platform: monochromatic
    name: '_B7'
    default_transition_length: 0s
    output: pwmB7
  - platform: monochromatic
    name: '_B8'
    default_transition_length: 0s
    output: pwmB8
  - platform: monochromatic
    name: '_B9'
    default_transition_length: 0s
    output: pwmB9
  - platform: monochromatic
    name: '_BA'
    default_transition_length: 0s
    output: pwmBa
  - platform: monochromatic
    name: '_BB'
    default_transition_length: 0s
    output: pwmBb
  - platform: monochromatic
    name: '_BC'
    default_transition_length: 0s
    output: pwmBc
  - platform: monochromatic
    name: '_BD'
    default_transition_length: 0s
    output: pwmBd
  - platform: monochromatic
    name: '_BE'
    default_transition_length: 0s
    output: pwmBe
  - platform: monochromatic
    name: '_BF'
    default_transition_length: 0s
    output: pwmBf
