pca9685:
  - id: ${id_pca9685_0}
    address: ${addr_pca9685_0}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_1}
    address: ${addr_pca9685_1}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_2}
    address: ${addr_pca9685_2}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_3}
    address: ${addr_pca9685_3}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_4}
    address: ${addr_pca9685_4}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_5}
    address: ${addr_pca9685_5}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_6}
    address: ${addr_pca9685_6}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_7}
    address: ${addr_pca9685_7}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_8}
    address: ${addr_pca9685_8}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_9}
    address: ${addr_pca9685_9}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_A}
    address: ${addr_pca9685_A}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_B}
    address: ${addr_pca9685_B}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_C}
    address: ${addr_pca9685_C}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_D}
    address: ${addr_pca9685_D}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_E}
    address: ${addr_pca9685_E}
    frequency: ${pwm_frequency}
  - id: ${id_pca9685_F}
    address: ${addr_pca9685_F}
    frequency: ${pwm_frequency}
