substitutions:
  esphome_name: "eth01-00"
  esphome_friendly_name: "WT32-eth01-00"

# I2C Port settings  
  i2c_sda: "21"
  i2c_scl: "22"
  i2c_scan: "true"
  i2c_id: "bus_a"

esphome:
  name: ${esphome_name}
  friendly_name: ${esphome_friendly_name}

esp32:
# https://docs.platformio.org/en/latest/boards/espressif32/wt32-eth01.html
  board: wt32-eth01
  framework:
    type: arduino

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 0
  power_pin: GPIO16

# Enable logging
logger:

# Enable Home Assistant API
api:

button:
  - platform: restart
    name: "Restart ${esphome_name}"
