substitutions:
  esphome_name: "ju-bd-00"
  esphome_friendly_name: "Hjulby-Block-Detection-00"

# PCF8574N & PCF8575
# 8bit portudvidelse I2C (2 wire) interface DIL16 Adresserbar til 
  id_pcf8574_0: "pcf8574_hub0"
  id_pcf8574_1: "pcf8574_hub1"
  id_pcf8574_2: "pcf8574_hub2"
  id_pcf8574_3: "pcf8574_hub3"
  id_pcf8574_4: "pcf8574_hub4"
  id_pcf8574_5: "pcf8574_hub5"
  id_pcf8574_6: "pcf8574_hub6"
  id_pcf8574_7: "pcf8574_hub7"
  
# hex:  0x20 0x21 0x22 0x23 0x24 0x25 0x26 0x27
  addr_pcf8574_0: "0x20"
  addr_pcf8574_1: "0x21"
  addr_pcf8574_2: "0x22"
  addr_pcf8574_3: "0x23"
  addr_pcf8574_4: "0x24"
  addr_pcf8574_5: "0x25"
  addr_pcf8574_6: "0x26"
  addr_pcf8574_7: "0x27"

# I2C Port settings  
  i2c_sda: "21"
  i2c_scl: "22"
  i2c_scan: "true"
  i2c_id: "bus_a"

  track_delayed_off: 1000ms

esphome:
  name: ${esphome_name}
  friendly_name: ${esphome_friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_omjk

ota:
  password: !secret ota_pass_omjk

wifi:
  networks:
  - ssid: !secret wifi_ssid_omjk
    password: !secret wifi_password_omjk
  - ssid: !secret wifi_ssid_sekt
    password: !secret wifi_password_sekt

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esphome_name} Fallback Hotspot"
    password: !secret ap_password_omjk
    
captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address ${esphome_name}"
    ssid:
      name: "Connected SSID ${esphome_name}"
    bssid:
      name: "Connected BSSID ${esphome_name}"
    mac_address:
      name: "Mac Wifi Address ${esphome_name}"

button:
  - platform: restart
    name: "Restart ${esphome_name}"

i2c:
  - id: ${i2c_id}
    sda: ${i2c_sda}
    scl: ${i2c_scl}
    scan: ${i2c_scan}  

# I2C_IO_Interface with PCF8574
<<: !include ./I2C_IO_PCF8574/.pcf8574_ids.yaml
<<: !include ./I2C_IO_PCF8574/.pcf8574_input.yaml
