substitutions:
  esphome_name: "pca9685-00"

# PCA9685 Kilde: https://esphome.io/components/output/pca9685
# id (Optional, ID): 
#   The id to use for this pca9685 component. 
#   Use this if you have multiple PCA9685s connected at the same time
  id_hub0: "pca9685_hub0"
  id_hub1: "pca9685_hub1"
  id_hub2: "pca9685_hub2"
  id_hub3: "pca9685_hub3"
  
# address (Optional, int): 
#   The I²C address of the driver. Defaults to 0x40.
  addr_hub0: "0x40"
  addr_hub1: "0x41"
  addr_hub2: "0x42"
  addr_hub3: "0x43"
  
# frequency (Optional, float): 
#   The frequency to let the component drive all PWM outputs at. 
#   Must be in range from 24Hz to 1525.88Hz. Default 1000Hz.  
  frequency_hub0: 200Hz
  frequency_hub1: 200Hz
  frequency_hub2: 500Hz
  frequency_hub3: 500Hz

# I²C Bus  Kilde: https://esphome.io/components/i2c#i2c
#   sda (Optional, Pin): The pin for the data line of the I²C bus. 
#     Defaults to the default of your board (usually GPIO21 for ESP32 and GPIO4 for ESP8266).
#   scl (Optional, Pin): The pin for the clock line of the I²C bus. 
#     Defaults to the default of your board (usually GPIO22 for ESP32 and GPIO5 for ESP8266).
#   scan (Optional, boolean): If ESPHome should do a search of the I²C address space on startup. 
#     Defaults to true.
#   frequency (Optional, float): Set the frequency the I²C bus should operate on.
#     Defaults to 50kHz. Values are 10kHz, 50kHz, 100kHz, 200kHz, … 800kHz
#   id (Optional, ID): Manually specify the ID for this I²C bus if you need multiple I²C buses.
#
# i2c bus_a
  i2c_sda: "21"
  i2c_scl: "22"
  i2c_scan: "true"
  i2c_id: "bus_a"

esphome:
  name: ${esphome_name}
  friendly_name: ${esphome_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key_omjk

ota:
  password: !secret ota_pass_omjk
wifi:
  networks:
  - ssid: !secret wifi_ssid_omjk
    password: !secret wifi_password_omjk
  - ssid: !secret wifi_ssid_sekt
    password: !secret wifi_password_sekt

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${esphome_name} Fallback Hotspot"
    password: !secret ap_password_omjk

captive_portal:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address ${esphome_name}"
    ssid:
      name: "Connected SSID ${esphome_name}"
    bssid:
      name: "Connected BSSID ${esphome_name}"
    mac_address:
      name: "Mac Wifi Address ${esphome_name}"

button:
  - platform: restart
    name: "Restart ${esphome_name}"

i2c:
  id: ${i2c_id}
  sda: ${i2c_sda}
  scl: ${i2c_scl}
  scan: ${i2c_scan}  

# Example configuration entry
pca9685:
  - id: ${id_hub0}
    address: ${addr_hub0}
    frequency: ${frequency_hub0}
  - id: ${id_hub1}
    address: ${addr_hub1}
    frequency: ${frequency_hub1}
  
# Individual outputs
# Output Component Kilde: https://esphome.io/components/output/
#   Configuration variables:
#     id (Required, ID): The id to use for this output component.
#     power_supply (Optional, ID): The power supply to connect to this output. When the output is enabled, the power supply will automatically be switched on too.
#     inverted (Optional, boolean): If the output should be treated as inverted. Defaults to false.
#   Float outputs only:
#     min_power (Optional, float): Sets the minimum output value of this output platform. Must be in range from 0 to max_power. Defaults to 0. If zero_means_zero is false this will be output value when the entity is turned off.
#     max_power (Optional, float): Sets the maximum output value of this output platform. Must be in range from min_power to 1. Defaults to 1.
#     zero_means_zero (Optional, boolean): Sets the output to use actual 0 instead of min_power. Defaults to false.
output:
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 0
    id: pwm00
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 1
    id: pwm01
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 2
    id: pwm02
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 3
    id: pwm03
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 4
    id: pwm04
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 5
    id: pwm05
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 6
    id: pwm06
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 7
    id: pwm07
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 8
    inverted: true
    id: pwm08
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 9
    inverted: true
    id: pwm09
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 10
    inverted: true
    id: pwm0a
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 11
    inverted: true
    id: pwm0b
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 12
    inverted: true
    id: pwm0c
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 13
    inverted: true
    id: pwm0d
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 14
    inverted: true
    id: pwm0e
  - platform: pca9685
    pca9685_id: ${id_hub0}
    channel: 15
    inverted: true
    id: pwm0f

# Hub1
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 0
    id: pwm10
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 1
    id: pwm11
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 2
    id: pwm12
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 3
    id: pwm13
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 4
    id: pwm14
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 5
    id: pwm15
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 6
    id: pwm16
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 7
    id: pwm17
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 8
    inverted: true
    id: pwm18
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 9
    inverted: true
    id: pwm19
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 10
    inverted: true
    id: pwm1a
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 11
    inverted: true
    id: pwm1b
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 12
    inverted: true
    id: pwm1c
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 13
    inverted: true
    id: pwm1d
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 14
    inverted: true
    id: pwm1e
  - platform: pca9685
    pca9685_id: ${id_hub1}
    channel: 15
    inverted: true
    id: pwm1f

# Light Component kilde: https://esphome.io/components/light/
# Monochromatic Light Kilde: https://esphome.io/components/light/monochromatic#monochromatic-light
#   Configuration variables:
#     name (Required, string): The name of the light.
#     output (Required, ID): The id of the float Output Component to use for this light.
#     effects (Optional, list): A list of light effects to use for this light.
#     id (Optional, ID): Manually specify the ID used for code generation.
light:
  - platform: monochromatic
    name: '_00'
    default_transition_length: 0s
    output: pwm00
  - platform: monochromatic
    name: '_01'
    default_transition_length: 0s
    output: pwm01
  - platform: monochromatic
    name: '_02'
    default_transition_length: 0s
    output: pwm02
  - platform: monochromatic
    name: '_03'
    default_transition_length: 0s
    output: pwm03
  - platform: monochromatic
    name: '_04'
    default_transition_length: 0s
    output: pwm04
  - platform: monochromatic
    name: '_05'
    default_transition_length: 0s
    output: pwm05
  - platform: monochromatic
    name: '_06'
    default_transition_length: 0s
    output: pwm06
  - platform: monochromatic
    name: '_07'
    default_transition_length: 0s
    output: pwm07
  - platform: monochromatic
    name: '_08'
    default_transition_length: 0s
    output: pwm08
  - platform: monochromatic
    name: '_09'
    default_transition_length: 0s
    output: pwm09
  - platform: monochromatic
    name: '_0A'
    default_transition_length: 0s
    output: pwm0a
  - platform: monochromatic
    name: '_0B'
    default_transition_length: 0s
    output: pwm0b
  - platform: monochromatic
    name: '_0C'
    default_transition_length: 0s
    output: pwm0c
  - platform: monochromatic
    name: '_0D'
    default_transition_length: 0s
    output: pwm0d
  - platform: monochromatic
    name: '_0E'
    default_transition_length: 0s
    output: pwm0e
  - platform: monochromatic
    name: '_0F'
    default_transition_length: 0s
    output: pwm0f

  - platform: monochromatic
    name: '_10'
    default_transition_length: 0s
    output: pwm10
  - platform: monochromatic
    name: '_11'
    default_transition_length: 0s
    output: pwm11
  - platform: monochromatic
    name: '_12'
    default_transition_length: 0s
    output: pwm12
  - platform: monochromatic
    name: '_13'
    default_transition_length: 0s
    output: pwm13
  - platform: monochromatic
    name: '_14'
    default_transition_length: 0s
    output: pwm14
  - platform: monochromatic
    name: '_15'
    default_transition_length: 0s
    output: pwm15
  - platform: monochromatic
    name: '_16'
    default_transition_length: 0s
    output: pwm16
  - platform: monochromatic
    name: '_17'
    default_transition_length: 0s
    output: pwm17
  - platform: monochromatic
    name: '_18'
    default_transition_length: 0s
    output: pwm18
  - platform: monochromatic
    name: '_19'
    default_transition_length: 0s
    output: pwm19
  - platform: monochromatic
    name: '_1A'
    default_transition_length: 0s
    output: pwm1a
  - platform: monochromatic
    name: '_1B'
    default_transition_length: 0s
    output: pwm1b
  - platform: monochromatic
    name: '_1C'
    default_transition_length: 0s
    output: pwm1c
  - platform: monochromatic
    name: '_1D'
    default_transition_length: 0s
    output: pwm1d
  - platform: monochromatic
    name: '_1E'
    default_transition_length: 0s
    output: pwm1e
  - platform: monochromatic
    name: '_1F'
    default_transition_length: 0s
    output: pwm1f

# RGB Light Kilde: https://esphome.io/components/light/rgb.html?highlight=rgb
#   Configuration variables:
#     name (Required, string): The name of the light.
#     red (Required, ID): The id of the float Output Component to use for the red channel.
#     green (Required, ID): The id of the float Output Component to use for the green channel.
#     blue (Required, ID): The id of the float Output Component to use for the blue channel.
#     effects (Optional, list): A list of light effects to use for this light.
#     id (Optional, ID): Manually specify the ID used for code generation.
#  - platform: rgb
#    name: '_Color'
#    red: pwm0d
#    green: pwm0e
#    blue: pwm0f
