sequence:
  - action: group.set
    metadata: {}
    data:
      object_id: synkron_led_blink
      add_entities: "{{ led_blink }}"
alias: Blink_Add_Entities
description: ""
fields:
  led_blink:
    selector:
      text: null
    default: "{{ led_off }}"
