sequence:
  - action: group.set
    metadata: {}
    data:
      object_id: synkron_led_blink
      remove_entities: "{{ led_blink }}"
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: "{{ led_blink }}"
alias: Blink_Remove_Entities
description: ""
fields:
  led_blink:
    selector:
      text: null
    default: "{{ led_off }}"
