# Individual outputs
# Output Component Kilde: https://esphome.io/components/output/
#   Configuration variables:
#     id (Required, ID): The id to use for this output component.
#     power_supply (Optional, ID): The power supply to connect to this output. When the output is enabled, the power supply will automatically be switched on too.
#     inverted (Optional, boolean): If the output should be treated as inverted. Defaults to false.
#   Float outputs only:
#     min_power (Optional, float): Sets the minimum output value of this output platform. Must be in range from 0 to max_power. Defaults to 0. If zero_means_zero is false this will be output value when the entity is turned off.
#     max_power (Optional, float): Sets the maximum output value of this output platform. Must be in range from min_power to 1. Defaults to 1.
#     zero_means_zero (Optional, boolean): Sets the output to use actual 0 instead of min_power. Defaults to false.
output:
# Hub0
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 0
    id: pwm00
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 1
    id: pwm01
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 2
    id: pwm02
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 3
    id: pwm03
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 4
    id: pwm04
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 5
    id: pwm05
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 6
    id: pwm06
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 7
    id: pwm07
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 8
    id: pwm08
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 9
    id: pwm09
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 10
    id: pwm0a
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 11
    id: pwm0b
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 12
    id: pwm0c
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 13
    id: pwm0d
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 14
    id: pwm0e
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}0
    channel: 15
    id: pwm0f
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
# Hub1
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 0
    id: pwm10
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 1
    id: pwm11
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 2
    id: pwm12
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 3
    id: pwm13
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 4
    id: pwm14
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 5
    id: pwm15
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 6
    id: pwm16
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 7
    id: pwm17
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 8
    id: pwm18
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 9
    id: pwm19
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 10
    id: pwm1a
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 11
    id: pwm1b
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 12
    id: pwm1c
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 13
    id: pwm1d
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 14
    id: pwm1e
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}1
    channel: 15
    id: pwm1f
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
# Hub2
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 0
    id: pwm20
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 1
    id: pwm21
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 2
    id: pwm22
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 3
    id: pwm23
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 4
    id: pwm24
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 5
    id: pwm25
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 6
    id: pwm26
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 7
    id: pwm27
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 8
    id: pwm28
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 9
    id: pwm29
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 10
    id: pwm2a
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 11
    id: pwm2b
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 12
    id: pwm2c
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 13
    id: pwm2d
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 14
    id: pwm2e
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
  - platform: pca9685
    pca9685_id: ${id_pca9685}2
    channel: 15
    id: pwm2f
    inverted: false
    min_power: 0.00
    max_power: 1.00
    zero_means_zero: false
